[package]
name = "conducto-nom"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.0"
bitflags = "1.1.0"
failure = "0.1.5"
failure_derive = "0.1.5"
