[package]
name = "conducto-nom"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.2"
bitflags = "1.2.1"
failure = "0.1.8"
failure_derive = "0.1.8"

[dev-dependencies]
rand = "0.7"
